### PR TITLE
Update publications.bib

### PR DESCRIPTION
**Pull request by JacobGlennAyers**
Added in working pdf link

### CODE REVIEW

**Comment by JacobGlennAyers** [comment]
Not entirely certain what the difference between the url and eprint field is. I just changed the eprint field to a working link to a pdf that was on my google scholar.

**Comment by ntlhui** [comment]
the `eprint` field always produces an arXiv link.  See https://info.arxiv.org/help/hypertex/bibstyles/index.html.

If there is no arXiv copy, do not include eprint.

Lack of documentation will be noted in a separate issue.

**Review by ntlhui — CHANGES_REQUESTED** [review]
Remove eprint unless arXiv copy exists

**Comment by ntlhui** [comment]
@JacobGlennAyers @Sean1572 @sprestrelski does an arXiv copy exist? Please also update this branch.

**Pull request closed without merging**
